version: "3.8"

services:
  app:
    build:
        context: ./
        dockerfile: ./builds/nodejs.Dockerfile
    restart: always
    ports:
      - "${APP}:3000"
    volumes: 
      - ./src:/usr/app
      - node_modules:/usr/data/node_modules
    networks: 
      - rede
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:4.2
    restart: always
    volumes:
      - db_data:/data/db
    networks:
      - rede
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: blog

  mongo-express:
    image: mongo-express:1.0.0-alpha
    restart: always
    networks:
      - rede
    ports:
      - 8080:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    depends_on:
      - mongo

  redis:
    image: redis:6
    restart: always
    networks:
      - rede


volumes: 
  db_data:
  node_modules:

networks: 
  rede: